{{- if and .Values.testing.aiAutomatedTesting.enabled .Values.testing.aiAutomatedTesting.useSecretsforAnthropicApiKey (not .Values.testing.aiAutomatedTesting.anthropicApiKeySecrets.existingSecret) .Values.testing.aiAutomatedTesting.anthropicApiKeySecrets.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akto.fullname" . }}-ai-automated-testing
  labels:
  {{- include "akto.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.testing.aiAutomatedTesting.secretKey }}: {{ .Values.testing.aiAutomatedTesting.anthropicApiKeySecrets.apiKey | toString | b64enc | quote }}
{{- end }}
