{{- if and .Values.testing.aktoApiSecurityTesting.env.useSecretsForDatabaseAbstractorToken (not .Values.testing.aktoApiSecurityTesting.env.databaseAbstractorTokenSecrets.existingSecret) .Values.testing.aktoApiSecurityTesting.env.databaseAbstractorTokenSecrets.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akto.fullname" . }}-mini-testing
  labels:
  {{- include "akto.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.testing.aktoApiSecurityTesting.env.databaseAbstractorTokenSecrets.token | toString | b64enc | quote }}
{{- end }}
{{- if and .Values.testing.aktoApiSecurityPuppeteerReplay.env.useSecretsForLogSenderApiKey (not .Values.testing.aktoApiSecurityPuppeteerReplay.env.logSenderApiKeySecrets.existingSecret) .Values.testing.aktoApiSecurityPuppeteerReplay.env.logSenderApiKeySecrets.token }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akto.fullname" . }}-puppeteer-replay
  labels:
  {{- include "akto.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.testing.aktoApiSecurityPuppeteerReplay.env.logSenderApiKeySecrets.token | toString | b64enc | quote }}
{{- end }}
{{- if and .Values.testing.agentTesting.env.useSecretsForAnthropicApiKey (not .Values.testing.agentTesting.env.anthropicApiKeySecrets.existingSecret) .Values.testing.agentTesting.env.anthropicApiKeySecrets.anthropicSecretKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akto.fullname" . }}-agent-testing
  labels:
  {{- include "akto.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.testing.agentTesting.env.anthropicApiKeySecrets.anthropicSecretKey | toString | b64enc | quote }}
{{- end }}