{{ if .Values.keel.keel.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "akto.fullname" . }}-keel-{{ .Release.Namespace }}
  labels:
  {{- include "akto.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "akto.fullname" . }}-keel-{{ .Release.Namespace }}'
subjects:
- kind: ServiceAccount
  name: '{{ include "akto.fullname" . }}-keel'
  namespace: '{{ .Release.Namespace }}'
{{ end }}