{{- if and .Values.testing.aiAutomatedTesting.enabled .Values.testing.aiAutomatedTesting.useSecretsforModelApiKey (not .Values.testing.aiAutomatedTesting.modelApiKeySecrets.existingSecret) .Values.testing.aiAutomatedTesting.modelApiKeySecrets.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akto.fullname" . }}-ai-automated-testing
  labels:
  {{- include "akto.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.testing.aiAutomatedTesting.secretKey }}: {{ .Values.testing.aiAutomatedTesting.modelApiKeySecrets.apiKey | toString | b64enc | quote }}
{{- end }}
