{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "akto-k8s-ebpf-openshift.labels" . | nindent 4 }}
  {{- if or .Values.serviceAccount.sccAnnotation .Values.serviceAccount.annotations }}
  annotations:
    {{- if .Values.serviceAccount.sccAnnotation }}
    scc.openshift.io/scc: {{ .Values.scc.name | quote }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
