{{- if and .Values.env.useSecretsForDatabaseAbstractorToken (not .Values.env.databaseAbstractorTokenSecrets.existingSecret) .Values.env.databaseAbstractorTokenSecrets.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-token
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: api-gateway-logging
type: Opaque
data:
  token: {{ .Values.env.databaseAbstractorTokenSecrets.token | toString | b64enc | quote }}
{{- end }}
