apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account-eks
  namespace: {{ .Release.Namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.roleArn | quote }}
