tokens:
  env:
    databaseAbstractorToken: ""
    proxyUri: ""
    noProxy: ""
    testingDbLayerUrl: ""
    publicKey: ""
    privateKey: ""

mini_runtime: 
  aktoApiSecurityRuntime:
    env:
      aktoAccountName: Helios
      aktoConfigName: staging
      aktoInstanceType: RUNTIME
      aktoKafkaBrokerMal: localhost:29092
      aktoKafkaBrokerUrl: 127.0.0.1:29092
      aktoKafkaGroupIdConfig: asdf
      aktoKafkaMaxPollRecordsConfig: "100"
      aktoKafkaTopicName: akto.api.logs
      blockLogs: true
      aktoTrafficBatchSize: "100"
      aktoTrafficBatchTimeSecs: "10"
      puppeteerReplayServiceUrl: http://akto-puppeteer-replay:3000
      useHostName: true
      databaseAbstractorUrl: https://cyborg.akto.io
    enabled: true
    image:
      repository: public.ecr.aws/aktosecurity/akto-api-security-mini-runtime
      tag: 1.62.5_local
    imagePullPolicy: Always
    resources:
      requests:
        cpu: "180m"
        memory: "500Mi"
      limits:
        cpu: 3
        memory: "8Gi"
  kafka1:
    env:
      kafkaBrokerId: "1"
      kafkaCleanupPolicy: delete
      kafkaCreateTopics: akto.api.logs:3:3
      kafkaInterBrokerListenerName: LISTENER_DOCKER_EXTERNAL_LOCALHOST
      kafkaListenerSecurityProtocolMap: CONTROLLER:PLAINTEXT,LISTENER_DOCKER_EXTERNAL_LOCALHOST:PLAINTEXT,
        LISTENER_DOCKER_EXTERNAL_DIFFHOST:PLAINTEXT
      kafkaProcessRoles: "broker,controller"
      kafkaNodeId: "1"
      kafkaControllerQuorumVoters: "1@localhost:9094"
      kafkaControllerListenerNames: "CONTROLLER"
      kafkaClusterId: "c6a1b8e2-4f2a-4b2a-9c3f-1a2b3c4d5e6f"
      kafkaListeners: "CONTROLLER://0.0.0.0:9094,LISTENER_DOCKER_EXTERNAL_LOCALHOST://0.0.0.0:29092,LISTENER_DOCKER_EXTERNAL_DIFFHOST://0.0.0.0:9092"
      kafkaLogCleanerEnable: "true"
      kafkaLogRetentionBytes: "10737418240"
      kafkaLogRetentionCheckIntervalMs: "60000"
      kafkaLogRetentionHours: "5"
      kafkaLogSegmentBytes: "104857600"
      kafkaOffsetsTopicReplicationFactor: "1"
      kafkaTransactionStateLogMinIsr: "1"
      kafkaTransactionStateLogReplicationFactor: "1"
    image:
      repository: public.ecr.aws/aktosecurity/confluentinc-cp-kafka
      tag: 8.1.1-1-ubi9
    resources:
      requests:
        cpu: "50m"
        memory: "500Mi"
      limits:
        cpu: 2
        memory: "8Gi"
  ports:
  - port: 9092
    targetPort: 9092
  replicas: 1
  type: ClusterIP

testing:
  aktoApiSecurityTesting:
    env:
      aktoAccountName: Helios
      aktoConfigName: staging
      puppeteerReplayServiceUrl: http://localhost:3000
      databaseAbstractorUrl: https://cyborg.akto.io
      publicKey: ""
    image:
      repository: public.ecr.aws/aktosecurity/akto-api-security-mini-testing
      tag: 1.59.9_local
    resources:
      requests:
        cpu: "200m"
        memory: "500Mi"
      limits:
        cpu: 2
        memory: "8Gi"
  aktoApiSecurityPuppeteerReplay:
    image:
      repository: aktosecurity/akto-puppeteer-replay
      tag: latest
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 1
        memory: "2Gi"
      limits:
        cpu: 1
        memory: "4Gi"
  replicas: 1

keel:
  keel:
    env:
      awsAccessKeyId: ""
      awsRegion: ""
      awsSecretAccessKey: ""
      hipchatApprovalsBotName: ""
      hipchatApprovalsChannel: ""
      hipchatApprovalsPasswort: ""
      hipchatApprovalsUserName: ""
      hipchatChannels: ""
      hipchatToken: ""
      insecureRegistry: "true"
      mattermostEndpoint: ""
      notificationLevel: info
      webhookEndpoint: ""
    image:
      repository: keelhq/keel
      tag: latest
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
    enabled: true
  maxUnavailable: 1
  ports:
  - name: keel
    port: 9300
    protocol: TCP
    targetPort: 9300
  replicas: 1
  serviceAccount:
    annotations: {}
  type: LoadBalancer
kubernetesClusterDomain: cluster.local
