apiVersion: v2
name: akto-k8s-ebpf-openshift
description: Akto eBPF DaemonSet for OpenShift (configurable SCC, hostNetwork, BTF + host /proc mounts)
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - akto
  - openshift
  - scc
  - ebpf
  - security
home: "https://www.akto.io"
sources:
  - "https://github.com/akto-api-security/helm-charts"
maintainers:
  - name: Akto
    url: "https://www.akto.io"
