{{- if and .Values.threat_client.kafka1.useSasl .Values.threat_client.kafka1.env.useSecretsForSaslCredentials (not .Values.threat_client.kafka1.env.saslCredentialsSecrets.existingSecret) .Values.threat_client.kafka1.env.saslCredentialsSecrets.username .Values.threat_client.kafka1.env.saslCredentialsSecrets.password}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-threat-client-sasl" (include "akto.fullname" .) }}
  labels:
    {{- include "akto.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.threat_client.kafka1.env.saslCredentialsSecrets.username | b64enc }}
  password: {{ .Values.threat_client.kafka1.env.saslCredentialsSecrets.password | b64enc }}
{{- end }}
