{{- if and .Values.threat_client.aktoApiSecurityThreatClient.env.useSecretsForDatabaseAbstractorToken (not .Values.threat_client.aktoApiSecurityThreatClient.env.databaseAbstractorTokenSecrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akto.fullname" . }}-threat-client
  labels:
  {{- include "akto.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.threat_client.aktoApiSecurityThreatClient.env.databaseAbstractorTokenSecrets.token | toString | b64enc | quote }}
{{- end }}
