apiVersion: v1
kind: Service
metadata:
  name: {{ include "akto.fullname" . }}-mini-runtime
  labels:
  {{- include "akto.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.mini_runtime.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.mini_runtime.loadBalancerDNS }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.mini_runtime.loadBalancerDNS }}
    {{- end }}
spec:
  type: {{ .Values.mini_runtime.type }}
  selector:
    app: {{ include "akto.fullname" . }}-mini-runtime
  {{- include "akto.selectorLabels" . | nindent 4 }}
  ports:
  {{- if .Values.mini_runtime.kafka1.useSasl }}
  {{- .Values.ports.sasl | toYaml | nindent 4 -}}
  {{- else if .Values.mini_runtime.kafka1.useTls }}
  {{- .Values.ports.tls | toYaml | nindent 4 -}}
  {{- else }}
  {{- .Values.ports.default | toYaml | nindent 4 -}}
  {{- end }}
